### ISSUE TITLE
Errors Running Directly After Clone

### ISSUE THREAD

**Issue by Silent-Zebra** [rlcode/per#6]
I cloned the repository, ran cartpole_per.py, and got:

prioritized_memory.py:41: RuntimeWarning: divide by zero encountered in power
  is_weight = np.power(self.tree.n_entries * sampling_probabilities, -self.beta)
prioritized_memory.py:42: RuntimeWarning: invalid value encountered in true_divide
  is_weight /= is_weight.max()
Traceback (most recent call last):
  File "cartpole_per.py", line 201, in <module>
    agent.train_model()
  File "cartpole_per.py", line 117, in train_model
    states = np.vstack(mini_batch[0])
  File "AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

I reran a few times, and the error always eventually occurs, though at varying lengths of time before it happens.

**Comment by Silent-Zebra** [comment]
Apologies, I should have read before posting. Fix provided by stormont in this thread: https://github.com/rlcode/per/issues/4
